#:schema node_modules/wrangler/config-schema.json
name = "tbreak"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DATABASE"
database_name = "STATS"
database_id = "45e8bf6b-577c-4b69-bf31-f2feb7862a89"

[triggers]
# Once an hour on the 0th minute
crons = ["0 * * * *"]

[[queues.producers]]
binding = "QUEUE"
queue = "stats"

[[queues.consumers]]
queue = "stats"
max_batch_size = 20
max_batch_timeout = 30

[[tail_consumers]]
service = "axiom-tail"

[[kv_namespaces]]
binding = "CACHE"
id = "7e9aa78fc90f42a78e1a4690f0f313a9"
